let produtosJson = [
    { id: 1, type: 'Romance', name: 'É assim que acaba', img: 'img/books/romance/e-assim-que-acaba.jpeg', price: [68.99, 37.99, 25.12], formats: ['Capa Dura', 'Capa comum', 'Ebook'], author: 'Colleen Hoover', description: 'Considerado o livro do ano, que virou febre no TikTok e sozinho já acumulou mais de um milhão de exemplares vendidos no Brasil. É assim que acaba é o romance mais pessoal da carreira de Colleen Hoover, discutindo temas como violência doméstica e abuso psicológico de forma sensível e direta.' },
    { id: 2, type: 'Romance', name: 'É assim que começa', img: 'img/books/romance/e-assim-que-comeca.jpg', price: [60.00, 38.40, 24.43], formats: ['Capa Dura', 'Capa comum', 'Ebook'], author: 'Collen Hoover', description: 'Preparem os corações. Lily e Atlas estão de volta na aguardada sequência de É assim que acaba. É assim que começa chega para consagrar novamente Colleen Hoover como a autora mais vendida do Brasil.' },
    { id: 3, type: 'Romance', name: 'Enquanto eu não te encontro', img: 'img/books/romance/enquanto-nao-te-encontro.jpg', price: [40.00, 28.99, 19.90], formats: ['Capa Dura', 'Capa comum', 'Ebook'], author: 'Pedro Rhuas', description: 'Em seu livro de estreia, Pedro Rhuas traz uma história sobre amor à primeira vista, encontros e desencontros, cultura nordestina, música pop e drag queens.' },
    { id: 4, type: 'Romance', name: 'O lado feio do amor', img: 'img/books/romance/o-lado-feio-do-amor.jpg', price: [50.00, 38.40, 27.93], formats: ['Capa Dura', 'Capa comum', 'Ebook'], author: 'Collen Hoover', description: 'Quando começou a se envolver com Miles, Tate prometeu não se apaixonar. Mas vai descobrir que nenhuma regra é capaz de controlar o amor e o desejo..' },
    { id: 5, type: 'Romance', name: 'Os dois morrem no final', img: 'img/books/romance/os-dois-morrem-no-final.jpg', price: [60.00, 38.90, 27.23], formats: ['Capa Dura', 'Capa comum', 'Ebook'], author: 'Adam Silveira', description: 'No dia 5 de setembro, pouco depois da meia-noite, Mateo Torrez e Rufus Emeterio recebem uma ligação da Central da Morte. A notícia é devastadora: eles vão morrer naquele mesmo dia.' },
    { id: 6, type: 'Romance', name: 'Os sete maridos de Evelyn Hugo', img: 'img/books/romance/os-sete-maridos-de-evelyn-hugo.jpg', price: [62.00, 38.40, 19.19], formats: ['Capa Dura', 'Capa comum', 'Ebook'], author: 'Taylor Jenkins Reid', description: 'Com todo o esplendor que só a Hollywood do século passado pode oferecer, esta é uma narrativa inesquecível sobre os sacrifícios que fazemos por amor, o perigo dos segredos e o preço da fama.' },
    { id: 7, type: 'Romance', name: 'Todas as suas imperfeições', img: 'img/books/romance/todas-as-suas-imperfeicoes.jpg', price: [50.00, 38.40, 24.43], formats: ['Capa Dura', 'Capa comum', 'Ebook'], author: 'Collen Hoover', description: 'Uma inesquecível história da rainha do drama Colleen Hoover, Todas as suas (im)perfeições fala sobre um casamento conturbado e uma promessa esquecida que pode ser capaz de salvá-lo.' },
    { id: 8, type: 'Romance', name: 'Vemerlho Branco Sangue Azul', img: 'img/books/romance/vermelho-branco-sangue-azul.jpg', price: [48.99, 35.70, 34.90], formats: ['Capa Dura', 'Capa comum', 'Ebook'], author: 'Casey McQuiston', description: 'O que pode acontecer quando o filho da presidenta dos Estados Unidos se apaixona pelo príncipe da Inglaterra?' },
    { id: 9, type: 'Romance', name: 'After 1', img: 'img/books/romance/after-1.jpg', price: [69.00, 32.99, 27.90], formats: ['Capa Dura', 'Capa comum', 'Ebook'], author: 'Anna Todd', description: 'Depois de bater a marca de um bilhão de acessos na plataforma de leitura Wattpad ao transformar os integrantes da banda One Direction em personagens de uma história de amor sexy, a série After vira livro e promete ser o novo fenômeno editorial.' },
    { id: 10, type: 'Romance', name: 'Quinze dias', img: 'img/books/romance/quinze-dias.jpg', price: [40.00, 29.00, 23.94], formats: ['Capa Dura', 'Capa comum', 'Ebook'], author: 'Vitor Martins', description: 'Felipe está esperando por esse momento desde que as aulas começaram: o início das férias de julho. Finalmente ele vai poder passar alguns dias longe da escola e dos colegas que o maltratam.' },
    { id: 11, type: 'Romance', name: 'Todo esse tempo', img: 'img/books/romance/todo-esse-tempo.jpg', price: [40.00, 29.10, 26.60], formats: ['Capa Dura', 'Capa comum', 'Ebook'], author: 'Rachael Lippincott', description: 'Kyle e Kimberly são o casal perfeito. Pelo menos, é o que Kyle acha. Por isso, quando Kimberly termina com ele na noite da festa de formatura, o mundo inteiro do garoto vira de cabeça para baixo - literalmente. O carro deles capota após sofrerem um acidente e, quando Kyle acorda no hospital, descobre que teve uma lesão cerebral. Kimberly está morta. E ninguém consegue entender a sua dor.' },
    { id: 12, type: 'Romance', name: 'Minha versão de você', img: 'img/books/romance/minha-versao-de-voce.jpg', price: [35.00, 20.00, 10.00], formats: ['Capa Dura', 'Capa comum', 'Ebook'], author: 'Christina Lauren', description: 'Há três anos a família de Tanner Scott se mudou da Califórnia para Utah, fazendo com que sua bissexualidade voltasse para o armário. Agora, com apenas mais um semestre até o fim das aulas no colegial e seu tão sonhado futuro em uma universidade longe da família, ele só deseja que o tempo passe mais depressa.' },
]   